name: epicplugin
version: '${project.version}'
main: staff.main.Epicplugin
author: Not_staff
api-version: '1.18'
commands:
  epicplugin:
    description: Plugin main command :D
    aliases:
      - ep
  heal:
    description: with this command you can set the hearts and the food bar
    usage: /<command>
    aliases:
      - epicplugin:heal
      - ep:heal
permissions:
  epicplugin.heal:
    description: Used to heal a player
    default: false
